# Generated by Django 4.2.4 on 2023-08-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
    ]
