# Generated by Django 4.2.4 on 2023-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.CharField(choices=[('1', 'Not Start Yet'), ('2', 'Doing'), ('3', 'Finish')], max_length=3),
        ),
    ]
