# Generated by Django 4.2.4 on 2023-08-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_updated_todo_user_alter_todo_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
