# Generated by Django 4.2.4 on 2023-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_options_todo_description_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complete',
            field=models.CharField(choices=[('1', 'Doing'), ('2', 'Not Start Yet'), ('3', 'Finish')], default=1, max_length=3),
        ),
    ]
